const EVENT_STORE_ACCESS_REQUESTED = 'EVENT_STORE_ACCESS_REQUESTED'
const EVENT_STORE_ACCESS_GRANTED = 'EVENT_STORE_ACCESS_GRANTED'
const EVENT_STORE_ACCESS_REVOKED = 'EVENT_STORE_ACCESS_REVOKED'

const CLI_COMMAND_RECEIVED = 'CLI_COMMAND_RECEIVED'

module.exports = {
  EVENT_STORE_ACCESS_REQUESTED,
  EVENT_STORE_ACCESS_GRANTED,
  EVENT_STORE_ACCESS_REVOKED,
  CLI_COMMAND_RECEIVED
}

